/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GiveRouteImport } from './routes/give'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BecomeBlessingSponsorRouteImport } from './routes/become-blessing-sponsor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SponsorDashboardRouteImport } from './routes/sponsor.dashboard'
import { Route as NgoOnboardingRouteImport } from './routes/ngo.onboarding'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as MeGivingRouteImport } from './routes/me.giving'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CampaignHandleRouteImport } from './routes/campaign.$handle'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminNgoDashboardRouteImport } from './routes/admin.ngo-dashboard'
import { Route as AdminCommandCenterRouteImport } from './routes/admin.command-center'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify-webhook'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicGoLiveReportRouteImport } from './routes/api/public/go-live-report'
import { Route as ApiPublicCategoriesTreeRouteImport } from './routes/api/public/categories-tree'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeBlessingSponsorRoute = BecomeBlessingSponsorRouteImport.update({
  id: '/become-blessing-sponsor',
  path: '/become-blessing-sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorDashboardRoute = SponsorDashboardRouteImport.update({
  id: '/sponsor/dashboard',
  path: '/sponsor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoOnboardingRoute = NgoOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => NgoRoute,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MeGivingRoute = MeGivingRouteImport.update({
  id: '/me/giving',
  path: '/me/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const CampaignHandleRoute = CampaignHandleRouteImport.update({
  id: '/campaign/$handle',
  path: '/campaign/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/admin/sponsors',
  path: '/admin/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNgoDashboardRoute = AdminNgoDashboardRouteImport.update({
  id: '/admin/ngo-dashboard',
  path: '/admin/ngo-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandCenterRoute = AdminCommandCenterRouteImport.update({
  id: '/admin/command-center',
  path: '/admin/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify-webhook',
  path: '/api/public/shopify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoLiveReportRoute = ApiPublicGoLiveReportRouteImport.update({
  id: '/api/public/go-live-report',
  path: '/api/public/go-live-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCategoriesTreeRoute = ApiPublicCategoriesTreeRouteImport.update({
  id: '/api/public/categories-tree',
  path: '/api/public/categories-tree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-blessing-sponsor': typeof BecomeBlessingSponsorRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/give': typeof GiveRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/ngo-dashboard': typeof AdminNgoDashboardRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/campaign/$handle': typeof CampaignHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/me/giving': typeof MeGivingRoute
  '/me/profile': typeof MeProfileRoute
  '/ngo/onboarding': typeof NgoOnboardingRoute
  '/sponsor/dashboard': typeof SponsorDashboardRoute
  '/api/public/categories-tree': typeof ApiPublicCategoriesTreeRoute
  '/api/public/go-live-report': typeof ApiPublicGoLiveReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-blessing-sponsor': typeof BecomeBlessingSponsorRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/give': typeof GiveRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/ngo-dashboard': typeof AdminNgoDashboardRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/campaign/$handle': typeof CampaignHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/me/giving': typeof MeGivingRoute
  '/me/profile': typeof MeProfileRoute
  '/ngo/onboarding': typeof NgoOnboardingRoute
  '/sponsor/dashboard': typeof SponsorDashboardRoute
  '/api/public/categories-tree': typeof ApiPublicCategoriesTreeRoute
  '/api/public/go-live-report': typeof ApiPublicGoLiveReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-blessing-sponsor': typeof BecomeBlessingSponsorRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/give': typeof GiveRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/ngo-dashboard': typeof AdminNgoDashboardRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/campaign/$handle': typeof CampaignHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/me/giving': typeof MeGivingRoute
  '/me/profile': typeof MeProfileRoute
  '/ngo/onboarding': typeof NgoOnboardingRoute
  '/sponsor/dashboard': typeof SponsorDashboardRoute
  '/api/public/categories-tree': typeof ApiPublicCategoriesTreeRoute
  '/api/public/go-live-report': typeof ApiPublicGoLiveReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-blessing-sponsor'
    | '/categories'
    | '/give'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/transparency'
    | '/admin/command-center'
    | '/admin/ngo-dashboard'
    | '/admin/sponsors'
    | '/campaign/$handle'
    | '/categories/$slug'
    | '/me/giving'
    | '/me/profile'
    | '/ngo/onboarding'
    | '/sponsor/dashboard'
    | '/api/public/categories-tree'
    | '/api/public/go-live-report'
    | '/api/public/health'
    | '/api/public/shopify-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-blessing-sponsor'
    | '/categories'
    | '/give'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/transparency'
    | '/admin/command-center'
    | '/admin/ngo-dashboard'
    | '/admin/sponsors'
    | '/campaign/$handle'
    | '/categories/$slug'
    | '/me/giving'
    | '/me/profile'
    | '/ngo/onboarding'
    | '/sponsor/dashboard'
    | '/api/public/categories-tree'
    | '/api/public/go-live-report'
    | '/api/public/health'
    | '/api/public/shopify-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-blessing-sponsor'
    | '/categories'
    | '/give'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/transparency'
    | '/admin/command-center'
    | '/admin/ngo-dashboard'
    | '/admin/sponsors'
    | '/campaign/$handle'
    | '/categories/$slug'
    | '/me/giving'
    | '/me/profile'
    | '/ngo/onboarding'
    | '/sponsor/dashboard'
    | '/api/public/categories-tree'
    | '/api/public/go-live-report'
    | '/api/public/health'
    | '/api/public/shopify-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeBlessingSponsorRoute: typeof BecomeBlessingSponsorRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  GiveRoute: typeof GiveRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  NgoRoute: typeof NgoRouteWithChildren
  TransparencyRoute: typeof TransparencyRoute
  AdminCommandCenterRoute: typeof AdminCommandCenterRoute
  AdminNgoDashboardRoute: typeof AdminNgoDashboardRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  CampaignHandleRoute: typeof CampaignHandleRoute
  MeGivingRoute: typeof MeGivingRoute
  MeProfileRoute: typeof MeProfileRoute
  SponsorDashboardRoute: typeof SponsorDashboardRoute
  ApiPublicCategoriesTreeRoute: typeof ApiPublicCategoriesTreeRoute
  ApiPublicGoLiveReportRoute: typeof ApiPublicGoLiveReportRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo': {
      id: '/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof NgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-blessing-sponsor': {
      id: '/become-blessing-sponsor'
      path: '/become-blessing-sponsor'
      fullPath: '/become-blessing-sponsor'
      preLoaderRoute: typeof BecomeBlessingSponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/dashboard': {
      id: '/sponsor/dashboard'
      path: '/sponsor/dashboard'
      fullPath: '/sponsor/dashboard'
      preLoaderRoute: typeof SponsorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/onboarding': {
      id: '/ngo/onboarding'
      path: '/onboarding'
      fullPath: '/ngo/onboarding'
      preLoaderRoute: typeof NgoOnboardingRouteImport
      parentRoute: typeof NgoRoute
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/giving': {
      id: '/me/giving'
      path: '/me/giving'
      fullPath: '/me/giving'
      preLoaderRoute: typeof MeGivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/campaign/$handle': {
      id: '/campaign/$handle'
      path: '/campaign/$handle'
      fullPath: '/campaign/$handle'
      preLoaderRoute: typeof CampaignHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ngo-dashboard': {
      id: '/admin/ngo-dashboard'
      path: '/admin/ngo-dashboard'
      fullPath: '/admin/ngo-dashboard'
      preLoaderRoute: typeof AdminNgoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command-center': {
      id: '/admin/command-center'
      path: '/admin/command-center'
      fullPath: '/admin/command-center'
      preLoaderRoute: typeof AdminCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify-webhook': {
      id: '/api/public/shopify-webhook'
      path: '/api/public/shopify-webhook'
      fullPath: '/api/public/shopify-webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/go-live-report': {
      id: '/api/public/go-live-report'
      path: '/api/public/go-live-report'
      fullPath: '/api/public/go-live-report'
      preLoaderRoute: typeof ApiPublicGoLiveReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/categories-tree': {
      id: '/api/public/categories-tree'
      path: '/api/public/categories-tree'
      fullPath: '/api/public/categories-tree'
      preLoaderRoute: typeof ApiPublicCategoriesTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface NgoRouteChildren {
  NgoOnboardingRoute: typeof NgoOnboardingRoute
}

const NgoRouteChildren: NgoRouteChildren = {
  NgoOnboardingRoute: NgoOnboardingRoute,
}

const NgoRouteWithChildren = NgoRoute._addFileChildren(NgoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeBlessingSponsorRoute: BecomeBlessingSponsorRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  GiveRoute: GiveRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  NgoRoute: NgoRouteWithChildren,
  TransparencyRoute: TransparencyRoute,
  AdminCommandCenterRoute: AdminCommandCenterRoute,
  AdminNgoDashboardRoute: AdminNgoDashboardRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  CampaignHandleRoute: CampaignHandleRoute,
  MeGivingRoute: MeGivingRoute,
  MeProfileRoute: MeProfileRoute,
  SponsorDashboardRoute: SponsorDashboardRoute,
  ApiPublicCategoriesTreeRoute: ApiPublicCategoriesTreeRoute,
  ApiPublicGoLiveReportRoute: ApiPublicGoLiveReportRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
