/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RequestHelpRouteImport } from './routes/request-help'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as MyBlessingsRouteImport } from './routes/my-blessings'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactMapRouteImport } from './routes/impact-map'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GiveABlessingRouteImport } from './routes/give-a-blessing'
import { Route as GiveRouteImport } from './routes/give'
import { Route as ExploreBlessingsRouteImport } from './routes/explore-blessings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BecomeBlessingSponsorRouteImport } from './routes/become-blessing-sponsor'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AboutMyblessingsRouteImport } from './routes/about-myblessings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SponsorDashboardRouteImport } from './routes/sponsor.dashboard'
import { Route as NgoOnboardingRouteImport } from './routes/ngo.onboarding'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as MeGivingRouteImport } from './routes/me.giving'
import { Route as DashboardPetriGraphRouteImport } from './routes/dashboard.petri-graph'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CampaignHandleRouteImport } from './routes/campaign.$handle'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminNgoDashboardRouteImport } from './routes/admin.ngo-dashboard'
import { Route as AdminMatchControlRouteImport } from './routes/admin.match-control'
import { Route as AdminGodViewRouteImport } from './routes/admin.god-view'
import { Route as AdminCommandCenterRouteImport } from './routes/admin.command-center'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify-webhook'
import { Route as ApiPublicPetriRecomputeRouteImport } from './routes/api/public/petri-recompute'
import { Route as ApiPublicPetriBloomRouteImport } from './routes/api/public/petri-bloom'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicGoLiveReportRouteImport } from './routes/api/public/go-live-report'
import { Route as ApiCategoriesTreeRouteImport } from './routes/api/categories/tree'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestHelpRoute = RequestHelpRouteImport.update({
  id: '/request-help',
  path: '/request-help',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBlessingsRoute = MyBlessingsRouteImport.update({
  id: '/my-blessings',
  path: '/my-blessings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactMapRoute = ImpactMapRouteImport.update({
  id: '/impact-map',
  path: '/impact-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveABlessingRoute = GiveABlessingRouteImport.update({
  id: '/give-a-blessing',
  path: '/give-a-blessing',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreBlessingsRoute = ExploreBlessingsRouteImport.update({
  id: '/explore-blessings',
  path: '/explore-blessings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeBlessingSponsorRoute = BecomeBlessingSponsorRouteImport.update({
  id: '/become-blessing-sponsor',
  path: '/become-blessing-sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMyblessingsRoute = AboutMyblessingsRouteImport.update({
  id: '/about-myblessings',
  path: '/about-myblessings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorDashboardRoute = SponsorDashboardRouteImport.update({
  id: '/sponsor/dashboard',
  path: '/sponsor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoOnboardingRoute = NgoOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => NgoRoute,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MeGivingRoute = MeGivingRouteImport.update({
  id: '/me/giving',
  path: '/me/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPetriGraphRoute = DashboardPetriGraphRouteImport.update({
  id: '/petri-graph',
  path: '/petri-graph',
  getParentRoute: () => DashboardRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const CampaignHandleRoute = CampaignHandleRouteImport.update({
  id: '/campaign/$handle',
  path: '/campaign/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/admin/sponsors',
  path: '/admin/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNgoDashboardRoute = AdminNgoDashboardRouteImport.update({
  id: '/admin/ngo-dashboard',
  path: '/admin/ngo-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchControlRoute = AdminMatchControlRouteImport.update({
  id: '/admin/match-control',
  path: '/admin/match-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGodViewRoute = AdminGodViewRouteImport.update({
  id: '/admin/god-view',
  path: '/admin/god-view',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandCenterRoute = AdminCommandCenterRouteImport.update({
  id: '/admin/command-center',
  path: '/admin/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify-webhook',
  path: '/api/public/shopify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPetriRecomputeRoute = ApiPublicPetriRecomputeRouteImport.update({
  id: '/api/public/petri-recompute',
  path: '/api/public/petri-recompute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPetriBloomRoute = ApiPublicPetriBloomRouteImport.update({
  id: '/api/public/petri-bloom',
  path: '/api/public/petri-bloom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoLiveReportRoute = ApiPublicGoLiveReportRouteImport.update({
  id: '/api/public/go-live-report',
  path: '/api/public/go-live-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesTreeRoute = ApiCategoriesTreeRouteImport.update({
  id: '/api/categories/tree',
  path: '/api/categories/tree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-myblessings': typeof AboutMyblessingsRoute
  '/about-us': typeof AboutUsRoute
  '/become-blessing-sponsor': typeof BecomeBlessingSponsorRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore-blessings': typeof ExploreBlessingsRoute
  '/give': typeof GiveRoute
  '/give-a-blessing': typeof GiveABlessingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact-map': typeof ImpactMapRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-blessings': typeof MyBlessingsRoute
  '/ngo': typeof NgoRouteWithChildren
  '/request-help': typeof RequestHelpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/god-view': typeof AdminGodViewRoute
  '/admin/match-control': typeof AdminMatchControlRoute
  '/admin/ngo-dashboard': typeof AdminNgoDashboardRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/campaign/$handle': typeof CampaignHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/petri-graph': typeof DashboardPetriGraphRoute
  '/me/giving': typeof MeGivingRoute
  '/me/profile': typeof MeProfileRoute
  '/ngo/onboarding': typeof NgoOnboardingRoute
  '/sponsor/dashboard': typeof SponsorDashboardRoute
  '/api/categories/tree': typeof ApiCategoriesTreeRoute
  '/api/public/go-live-report': typeof ApiPublicGoLiveReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/petri-bloom': typeof ApiPublicPetriBloomRoute
  '/api/public/petri-recompute': typeof ApiPublicPetriRecomputeRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-myblessings': typeof AboutMyblessingsRoute
  '/about-us': typeof AboutUsRoute
  '/become-blessing-sponsor': typeof BecomeBlessingSponsorRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore-blessings': typeof ExploreBlessingsRoute
  '/give': typeof GiveRoute
  '/give-a-blessing': typeof GiveABlessingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact-map': typeof ImpactMapRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-blessings': typeof MyBlessingsRoute
  '/ngo': typeof NgoRouteWithChildren
  '/request-help': typeof RequestHelpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/god-view': typeof AdminGodViewRoute
  '/admin/match-control': typeof AdminMatchControlRoute
  '/admin/ngo-dashboard': typeof AdminNgoDashboardRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/campaign/$handle': typeof CampaignHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/petri-graph': typeof DashboardPetriGraphRoute
  '/me/giving': typeof MeGivingRoute
  '/me/profile': typeof MeProfileRoute
  '/ngo/onboarding': typeof NgoOnboardingRoute
  '/sponsor/dashboard': typeof SponsorDashboardRoute
  '/api/categories/tree': typeof ApiCategoriesTreeRoute
  '/api/public/go-live-report': typeof ApiPublicGoLiveReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/petri-bloom': typeof ApiPublicPetriBloomRoute
  '/api/public/petri-recompute': typeof ApiPublicPetriRecomputeRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-myblessings': typeof AboutMyblessingsRoute
  '/about-us': typeof AboutUsRoute
  '/become-blessing-sponsor': typeof BecomeBlessingSponsorRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore-blessings': typeof ExploreBlessingsRoute
  '/give': typeof GiveRoute
  '/give-a-blessing': typeof GiveABlessingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact-map': typeof ImpactMapRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-blessings': typeof MyBlessingsRoute
  '/ngo': typeof NgoRouteWithChildren
  '/request-help': typeof RequestHelpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/god-view': typeof AdminGodViewRoute
  '/admin/match-control': typeof AdminMatchControlRoute
  '/admin/ngo-dashboard': typeof AdminNgoDashboardRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/campaign/$handle': typeof CampaignHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/petri-graph': typeof DashboardPetriGraphRoute
  '/me/giving': typeof MeGivingRoute
  '/me/profile': typeof MeProfileRoute
  '/ngo/onboarding': typeof NgoOnboardingRoute
  '/sponsor/dashboard': typeof SponsorDashboardRoute
  '/api/categories/tree': typeof ApiCategoriesTreeRoute
  '/api/public/go-live-report': typeof ApiPublicGoLiveReportRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/petri-bloom': typeof ApiPublicPetriBloomRoute
  '/api/public/petri-recompute': typeof ApiPublicPetriRecomputeRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-myblessings'
    | '/about-us'
    | '/become-blessing-sponsor'
    | '/categories'
    | '/dashboard'
    | '/explore-blessings'
    | '/give'
    | '/give-a-blessing'
    | '/how-it-works'
    | '/impact-map'
    | '/login'
    | '/marketplace'
    | '/my-blessings'
    | '/ngo'
    | '/request-help'
    | '/sitemap.xml'
    | '/transparency'
    | '/admin/command-center'
    | '/admin/god-view'
    | '/admin/match-control'
    | '/admin/ngo-dashboard'
    | '/admin/sponsors'
    | '/campaign/$handle'
    | '/categories/$slug'
    | '/dashboard/petri-graph'
    | '/me/giving'
    | '/me/profile'
    | '/ngo/onboarding'
    | '/sponsor/dashboard'
    | '/api/categories/tree'
    | '/api/public/go-live-report'
    | '/api/public/health'
    | '/api/public/petri-bloom'
    | '/api/public/petri-recompute'
    | '/api/public/shopify-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-myblessings'
    | '/about-us'
    | '/become-blessing-sponsor'
    | '/categories'
    | '/dashboard'
    | '/explore-blessings'
    | '/give'
    | '/give-a-blessing'
    | '/how-it-works'
    | '/impact-map'
    | '/login'
    | '/marketplace'
    | '/my-blessings'
    | '/ngo'
    | '/request-help'
    | '/sitemap.xml'
    | '/transparency'
    | '/admin/command-center'
    | '/admin/god-view'
    | '/admin/match-control'
    | '/admin/ngo-dashboard'
    | '/admin/sponsors'
    | '/campaign/$handle'
    | '/categories/$slug'
    | '/dashboard/petri-graph'
    | '/me/giving'
    | '/me/profile'
    | '/ngo/onboarding'
    | '/sponsor/dashboard'
    | '/api/categories/tree'
    | '/api/public/go-live-report'
    | '/api/public/health'
    | '/api/public/petri-bloom'
    | '/api/public/petri-recompute'
    | '/api/public/shopify-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-myblessings'
    | '/about-us'
    | '/become-blessing-sponsor'
    | '/categories'
    | '/dashboard'
    | '/explore-blessings'
    | '/give'
    | '/give-a-blessing'
    | '/how-it-works'
    | '/impact-map'
    | '/login'
    | '/marketplace'
    | '/my-blessings'
    | '/ngo'
    | '/request-help'
    | '/sitemap.xml'
    | '/transparency'
    | '/admin/command-center'
    | '/admin/god-view'
    | '/admin/match-control'
    | '/admin/ngo-dashboard'
    | '/admin/sponsors'
    | '/campaign/$handle'
    | '/categories/$slug'
    | '/dashboard/petri-graph'
    | '/me/giving'
    | '/me/profile'
    | '/ngo/onboarding'
    | '/sponsor/dashboard'
    | '/api/categories/tree'
    | '/api/public/go-live-report'
    | '/api/public/health'
    | '/api/public/petri-bloom'
    | '/api/public/petri-recompute'
    | '/api/public/shopify-webhook'
  fileRoutesById: FileRoutesById
}

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardPetriGraphRoute: typeof DashboardPetriGraphRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPetriGraphRoute: DashboardPetriGraphRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface NgoRouteChildren {
  NgoOnboardingRoute: typeof NgoOnboardingRoute
}

const NgoRouteChildren: NgoRouteChildren = {
  NgoOnboardingRoute: NgoOnboardingRoute,
}

const NgoRouteWithChildren = NgoRoute._addFileChildren(NgoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutMyblessingsRoute: AboutMyblessingsRoute,
  AboutUsRoute: AboutUsRoute,
  BecomeBlessingSponsorRoute: BecomeBlessingSponsorRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreBlessingsRoute: ExploreBlessingsRoute,
  GiveRoute: GiveRoute,
  GiveABlessingRoute: GiveABlessingRoute,
  HowItWorksRoute: HowItWorksRoute,
  ImpactMapRoute: ImpactMapRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyBlessingsRoute: MyBlessingsRoute,
  NgoRoute: NgoRouteWithChildren,
  RequestHelpRoute: RequestHelpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransparencyRoute: TransparencyRoute,
  AdminCommandCenterRoute: AdminCommandCenterRoute,
  AdminGodViewRoute: AdminGodViewRoute,
  AdminMatchControlRoute: AdminMatchControlRoute,
  AdminNgoDashboardRoute: AdminNgoDashboardRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  CampaignHandleRoute: CampaignHandleRoute,
  MeGivingRoute: MeGivingRoute,
  MeProfileRoute: MeProfileRoute,
  SponsorDashboardRoute: SponsorDashboardRoute,
  ApiCategoriesTreeRoute: ApiCategoriesTreeRoute,
  ApiPublicGoLiveReportRoute: ApiPublicGoLiveReportRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicPetriBloomRoute: ApiPublicPetriBloomRoute,
  ApiPublicPetri